/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateWeeklyQuizRequest } from '../../models/create-weekly-quiz-request';
import { WeeklyQuizResponse } from '../../models/weekly-quiz-response';

export interface CreateWeeklyQuiz$Params {
      body: CreateWeeklyQuizRequest
}

export function createWeeklyQuiz(http: HttpClient, rootUrl: string, params: CreateWeeklyQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<WeeklyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, createWeeklyQuiz.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeeklyQuizResponse>;
    })
  );
}

createWeeklyQuiz.PATH = '/weekly-quizzes';
