/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeeklyQuizResponse } from '../../models/weekly-quiz-response';

export interface GetWeeklyQuiz$Params {
  uuid: string;
}

export function getWeeklyQuiz(http: HttpClient, rootUrl: string, params: GetWeeklyQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<WeeklyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, getWeeklyQuiz.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeeklyQuizResponse>;
    })
  );
}

getWeeklyQuiz.PATH = '/weekly-quizzes/{uuid}';
