/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageWeeklyQuizResponse } from '../../models/page-weekly-quiz-response';

export interface GetWeeklyQuizzes$Params {
  weekStart?: string;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getWeeklyQuizzes(http: HttpClient, rootUrl: string, params?: GetWeeklyQuizzes$Params, context?: HttpContext): Observable<StrictHttpResponse<PageWeeklyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, getWeeklyQuizzes.PATH, 'get');
  if (params) {
    rb.query('weekStart', params.weekStart, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageWeeklyQuizResponse>;
    })
  );
}

getWeeklyQuizzes.PATH = '/weekly-quizzes';
