/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateWeeklyQuizRequest } from '../../models/update-weekly-quiz-request';
import { WeeklyQuizResponse } from '../../models/weekly-quiz-response';

export interface UpdateWeeklyQuiz$Params {
  uuid: string;
      body: UpdateWeeklyQuizRequest
}

export function updateWeeklyQuiz(http: HttpClient, rootUrl: string, params: UpdateWeeklyQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<WeeklyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, updateWeeklyQuiz.PATH, 'patch');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeeklyQuizResponse>;
    })
  );
}

updateWeeklyQuiz.PATH = '/weekly-quizzes/{uuid}';
