/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateLeaderboardEntryRequest } from '../../models/create-leaderboard-entry-request';
import { LeaderboardEntryResponse } from '../../models/leaderboard-entry-response';

export interface CreateLeaderboardEntry$Params {
      body: CreateLeaderboardEntryRequest
}

export function createLeaderboardEntry(http: HttpClient, rootUrl: string, params: CreateLeaderboardEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaderboardEntryResponse>> {
  const rb = new RequestBuilder(rootUrl, createLeaderboardEntry.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaderboardEntryResponse>;
    })
  );
}

createLeaderboardEntry.PATH = '/leaderboard-entries';
