/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageLeaderboardEntryResponse } from '../../models/page-leaderboard-entry-response';

export interface GetLeaderboardEntries$Params {
  leaderboardType?: 'GLOBAL' | 'WEEKLY' | 'CATEGORY';
  categoryUuid?: string;
  weeklyQuizUuid?: string;
  userUuid?: string;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getLeaderboardEntries(http: HttpClient, rootUrl: string, params?: GetLeaderboardEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<PageLeaderboardEntryResponse>> {
  const rb = new RequestBuilder(rootUrl, getLeaderboardEntries.PATH, 'get');
  if (params) {
    rb.query('leaderboardType', params.leaderboardType, {});
    rb.query('categoryUuid', params.categoryUuid, {});
    rb.query('weeklyQuizUuid', params.weeklyQuizUuid, {});
    rb.query('userUuid', params.userUuid, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageLeaderboardEntryResponse>;
    })
  );
}

getLeaderboardEntries.PATH = '/leaderboard-entries';
