/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignLessonQuestionRequest } from '../../models/assign-lesson-question-request';
import { LessonQuestionResponse } from '../../models/lesson-question-response';

export interface AssignQuestion1$Params {
      body: AssignLessonQuestionRequest
}

export function assignQuestion1(http: HttpClient, rootUrl: string, params: AssignQuestion1$Params, context?: HttpContext): Observable<StrictHttpResponse<LessonQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, assignQuestion1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LessonQuestionResponse>;
    })
  );
}

assignQuestion1.PATH = '/lesson-questions';
