/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LessonQuestionResponse } from '../../models/lesson-question-response';
import { UpdateLessonQuestionRequest } from '../../models/update-lesson-question-request';

export interface UpdateAssignment1$Params {
  id: number;
      body: UpdateLessonQuestionRequest
}

export function updateAssignment1(http: HttpClient, rootUrl: string, params: UpdateAssignment1$Params, context?: HttpContext): Observable<StrictHttpResponse<LessonQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAssignment1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LessonQuestionResponse>;
    })
  );
}

updateAssignment1.PATH = '/lesson-questions/{id}';
