spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
