/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDailyQuizRequest } from '../../models/create-daily-quiz-request';
import { DailyQuizResponse } from '../../models/daily-quiz-response';

export interface CreateDailyQuiz$Params {
      body: CreateDailyQuizRequest
}

export function createDailyQuiz(http: HttpClient, rootUrl: string, params: CreateDailyQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, createDailyQuiz.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyQuizResponse>;
    })
  );
}

createDailyQuiz.PATH = '/daily-quizzes';
