/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageDailyQuizResponse } from '../../models/page-daily-quiz-response';

export interface GetDailyQuizzes$Params {
  quizDate?: string;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getDailyQuizzes(http: HttpClient, rootUrl: string, params?: GetDailyQuizzes$Params, context?: HttpContext): Observable<StrictHttpResponse<PageDailyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, getDailyQuizzes.PATH, 'get');
  if (params) {
    rb.query('quizDate', params.quizDate, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageDailyQuizResponse>;
    })
  );
}

getDailyQuizzes.PATH = '/daily-quizzes';
