/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyQuizResponse } from '../../models/daily-quiz-response';

export interface GetDailyQuiz$Params {
  uuid: string;
}

export function getDailyQuiz(http: HttpClient, rootUrl: string, params: GetDailyQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, getDailyQuiz.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyQuizResponse>;
    })
  );
}

getDailyQuiz.PATH = '/daily-quizzes/{uuid}';
