/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyQuizResponse } from '../../models/daily-quiz-response';
import { UpdateDailyQuizRequest } from '../../models/update-daily-quiz-request';

export interface UpdateDailyQuiz$Params {
  uuid: string;
      body: UpdateDailyQuizRequest
}

export function updateDailyQuiz(http: HttpClient, rootUrl: string, params: UpdateDailyQuiz$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyQuizResponse>> {
  const rb = new RequestBuilder(rootUrl, updateDailyQuiz.PATH, 'patch');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyQuizResponse>;
    })
  );
}

updateDailyQuiz.PATH = '/daily-quizzes/{uuid}';
