/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateLessonRequest } from '../../models/create-lesson-request';
import { LessonResponse } from '../../models/lesson-response';

export interface CreateLesson$Params {
      body: CreateLessonRequest
}

export function createLesson(http: HttpClient, rootUrl: string, params: CreateLesson$Params, context?: HttpContext): Observable<StrictHttpResponse<LessonResponse>> {
  const rb = new RequestBuilder(rootUrl, createLesson.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LessonResponse>;
    })
  );
}

createLesson.PATH = '/lessons';
