/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LessonResponse } from '../../models/lesson-response';

export interface GetLesson$Params {
  uuid: string;
}

export function getLesson(http: HttpClient, rootUrl: string, params: GetLesson$Params, context?: HttpContext): Observable<StrictHttpResponse<LessonResponse>> {
  const rb = new RequestBuilder(rootUrl, getLesson.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LessonResponse>;
    })
  );
}

getLesson.PATH = '/lessons/{uuid}';
