/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LessonResponse } from '../../models/lesson-response';
import { UpdateLessonRequest } from '../../models/update-lesson-request';

export interface UpdateLesson$Params {
  uuid: string;
      body: UpdateLessonRequest
}

export function updateLesson(http: HttpClient, rootUrl: string, params: UpdateLesson$Params, context?: HttpContext): Observable<StrictHttpResponse<LessonResponse>> {
  const rb = new RequestBuilder(rootUrl, updateLesson.PATH, 'patch');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LessonResponse>;
    })
  );
}

updateLesson.PATH = '/lessons/{uuid}';
