/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignDailyQuizQuestionRequest {
  dailyQuizUuid: string;
  displayOrder?: number;
  questionUuid: string;
}
