/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignWeeklyQuizQuestionRequest {
  displayOrder?: number;
  questionUuid: string;
  weeklyQuizUuid: string;
}
