/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthenticationResponse {
  accessToken?: string;
  email?: string;
  firstname?: string;
  lastname?: string;
  refreshToken?: string;
  roles?: Array<string>;
  tenantUuid?: string;
  userUuid?: string;
}
