/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthenticationResponse {
  accessToken?: string;
  refreshToken?: string;
  roles?: Array<string>;
  tenantUuid?: string;
  /** @deprecated */token?: string;
  userUuid?: string;
}
