/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTenantRequest {
  country?: string;
  email?: string;
  examFocus?: string;
  name: string;
  phone?: string;
  slug: string;
}
