/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePlatformStaffRequest {
  email: string;
  firstname: string;
  lastname: string;
  positionName?: string;
  roles: Array<string>;
}
