/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLeaderboardEntryRequest {
  categoryUuid?: string;
  leaderboardType: 'GLOBAL' | 'WEEKLY' | 'CATEGORY';
  rankPosition?: number;
  score?: number;
  userUuid: string;
  weeklyQuizUuid?: string;
}
