/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DailyQuizQuestionResponse {
  dailyQuizUuid?: string;
  displayOrder?: number;
  id?: number;
  questionText?: string;
  questionUuid?: string;
}
