/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FindRolesQuery {
  description?: string;
  name?: string;
  page?: number;
  roleLevel?: string;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}
