/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FindStudentsQuery {
  email?: string;
  firstname?: string;
  lastname?: string;
  level?: number;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
  streakDays?: number;
  tenantUuid?: string;
  username?: string;
  xp?: number;
}
