/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FindTenantsQuery {
  country?: string;
  description?: string;
  examFocus?: string;
  name?: string;
  page?: number;
  phone?: string;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}
