/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FindStaffQuery {
  email?: string;
  firstname?: string;
  lastname?: string;
  page?: number;
  positionName?: string;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}
