/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GradingCriterionResponse {
  description?: string;
  keywords?: Array<string>;
  score?: number;
  title?: string;
  uuid?: string;
}
