/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LeaderboardEntryResponse {
  categoryUuid?: string;
  leaderboardType?: 'GLOBAL' | 'WEEKLY' | 'CATEGORY';
  rankPosition?: number;
  score?: number;
  userUuid?: string;
  uuid?: string;
  weeklyQuizUuid?: string;
}
