/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LessonQuestionResponse {
  displayOrder?: number;
  id?: number;
  lessonUuid?: string;
  questionText?: string;
  questionUuid?: string;
}
