/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LessonResponse {
  categoryName?: string;
  categoryUuid?: string;
  content?: string;
  isPremium?: boolean;
  title?: string;
  uuid?: string;
}
