/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageableObject } from '../models/pageable-object';
import { QuestionOptionResponseDto } from '../models/question-option-response-dto';
import { SortObject } from '../models/sort-object';
export interface PageQuestionOptionResponseDto {
  content?: Array<QuestionOptionResponseDto>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
