/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeaderboardEntryResponse } from '../models/leaderboard-entry-response';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageLeaderboardEntryResponse {
  content?: Array<LeaderboardEntryResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
