/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GetQuestionResponse } from '../models/get-question-response';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageGetQuestionResponse {
  content?: Array<GetQuestionResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
