/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageableObject } from '../models/pageable-object';
import { QuizSessionResponse } from '../models/quiz-session-response';
import { SortObject } from '../models/sort-object';
export interface PageQuizSessionResponse {
  content?: Array<QuizSessionResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
