/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DailyQuizQuestionResponse } from '../models/daily-quiz-question-response';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageDailyQuizQuestionResponse {
  content?: Array<DailyQuizQuestionResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
