/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PermissionResponse {
  code?: string;
  description?: string;
  level?: 'PLATFORM' | 'TENANT';
  uuid?: string;
}
