/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlatformUpdateTenantRequest {
  active?: boolean;
  country?: string;
  email?: string;
  examFocus?: string;
  logoUrl?: string;
  name: string;
  phone?: string;
}
