/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuestionOptionResponseDto {
  correct?: boolean;
  imageUrl?: string;
  optionText?: string;
  questionUuid?: string;
  uuid?: string;
}
