/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuizSessionResponse {
  categoryUuid?: string;
  completedAt?: string;
  correctAnswers?: number;
  dailyQuizUuid?: string;
  durationSeconds?: number;
  scorePercentage?: number;
  sessionType?: 'TRAINING' | 'DAILY' | 'WEEKLY';
  startedAt?: string;
  totalQuestions?: number;
  uuid?: string;
  weeklyQuizUuid?: string;
  xpEarned?: number;
}
