/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StaffResponse {
  email?: string;
  enabled?: boolean;
  firstname?: string;
  lastname?: string;
  platformStaff?: boolean;
  positionName?: string;
  roles?: Array<string>;
  tenantUuid?: string;
  uuid?: string;
}
