/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StartQuizSessionRequest {
  categoryUuid?: string;
  dailyQuizUuid?: string;
  sessionType: 'TRAINING' | 'DAILY' | 'WEEKLY';
  weeklyQuizUuid?: string;
}
