/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentResponse {
  email?: string;
  firstname?: string;
  lastname?: string;
  level?: number;
  tenantUuid?: string;
  username?: string;
  uuid?: string;
  xp?: number;
}
