/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentResponse {
  accountLocked?: boolean;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  lastModifiedDate?: string;
  lastname?: string;
  level?: number;
  username?: string;
  uuid?: string;
  xp?: number;
}
