/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentRegistrationRequest {
  dateOfBirth: string;
  email: string;
  firstname: string;
  lastname: string;
  password: string;
  username: string;
}
