/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantResponse {
  active?: boolean;
  country?: string;
  description?: string;
  email?: string;
  examFocus?: string;
  id?: number;
  lastModifiedDate?: string;
  logoUrl?: string;
  name?: string;
  phone?: string;
  slug?: string;
  uuid?: string;
}
