/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTenantRequest {
  country?: string;
  description?: string;
  email?: string;
  examFocus?: string;
  logoUrl?: string;
  name: string;
  phone?: string;
}
