/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateQuestionOptionForm {
  correct?: boolean;

  /**
   * Option image file
   */
  image?: Blob;
  optionText: string;
}
