/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePlatformStaffRequest {
  firstname?: string;
  lastname?: string;
  positionName?: string;
  roles?: Array<string>;
}
