/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProfileRequest {
  email?: string;
  firstname?: string;
  lastname?: string;
  phone?: string;
  username?: string;
}
