/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCategoryForm {
  description: string;

  /**
   * Category image file
   */
  image?: Blob;
  languageUuid?: string;
  name: string;
  parentUuid?: string;
  slug: string;
}
