/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserQuestionStatisticsResponse {
  attempts?: number;
  averageTimeSec?: number;
  correctAttempts?: number;
  id?: number;
  lastAttemptedAt?: string;
  masteryScore?: number;
  nextReviewAt?: string;
  questionText?: string;
  questionUuid?: string;
  sm2Easiness?: number;
  sm2Interval?: number;
  sm2Repetitions?: number;
}
