/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WeeklyQuizQuestionResponse {
  displayOrder?: number;
  id?: number;
  questionText?: string;
  questionUuid?: string;
  weeklyQuizUuid?: string;
}
