/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GradingCriterionResponse } from '../models/grading-criterion-response';
export interface WrittenAnswerConfigResponse {
  gradingCriteria?: Array<GradingCriterionResponse>;
  gradingStrategy?: 'EXACT_MATCH' | 'KEYWORD_MATCH' | 'RUBRIC' | 'SEMANTIC_SIMILARITY' | 'AI';
  maxScore?: number;
  minimumScoreThreshold?: number;
  referenceAnswer?: string;
  uuid?: string;
}
