/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageGetQuestionResponse } from '../../models/page-get-question-response';

export interface GetQuestions$Params {
  questionText?: string;
  difficultyLevel?: 'EASY' | 'MEDIUM' | 'HARD' | 'EXPERT';
  questionType?: 'MCQ' | 'TRUE_OR_FALSE' | 'STRUCTURAL' | 'ESSAY';
  categoryUuid?: string;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getQuestions(http: HttpClient, rootUrl: string, params?: GetQuestions$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGetQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, getQuestions.PATH, 'get');
  if (params) {
    rb.query('questionText', params.questionText, {});
    rb.query('difficultyLevel', params.difficultyLevel, {});
    rb.query('questionType', params.questionType, {});
    rb.query('categoryUuid', params.categoryUuid, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGetQuestionResponse>;
    })
  );
}

getQuestions.PATH = '/questions';
