/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetQuestionResponse } from '../../models/get-question-response';
import { UpdateQuestionForm } from '../../models/update-question-form';

export interface UpdateQuestion$Params {
  uuid: string;
      body?: UpdateQuestionForm
}

export function updateQuestion(http: HttpClient, rootUrl: string, params: UpdateQuestion$Params, context?: HttpContext): Observable<StrictHttpResponse<GetQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateQuestion.PATH, 'patch');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetQuestionResponse>;
    })
  );
}

updateQuestion.PATH = '/questions/{uuid}';
