/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindStudentsQuery } from '../../models/find-students-query';
import { PageStudentResponse } from '../../models/page-student-response';

export interface GetStudents$Params {
  query: FindStudentsQuery;
}

export function getStudents(http: HttpClient, rootUrl: string, params: GetStudents$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStudentResponse>> {
  const rb = new RequestBuilder(rootUrl, getStudents.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageStudentResponse>;
    })
  );
}

getStudents.PATH = '/admin/students';
