/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentDetailResponse } from '../../models/student-detail-response';

export interface GetStudentDetails$Params {
  uuid: string;
}

export function getStudentDetails(http: HttpClient, rootUrl: string, params: GetStudentDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, getStudentDetails.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentDetailResponse>;
    })
  );
}

getStudentDetails.PATH = '/admin/students/{uuid}';
