/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignDailyQuizQuestionRequest } from '../../models/assign-daily-quiz-question-request';
import { DailyQuizQuestionResponse } from '../../models/daily-quiz-question-response';

export interface AssignQuestion2$Params {
      body: AssignDailyQuizQuestionRequest
}

export function assignQuestion2(http: HttpClient, rootUrl: string, params: AssignQuestion2$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyQuizQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, assignQuestion2.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyQuizQuestionResponse>;
    })
  );
}

assignQuestion2.PATH = '/daily-quiz-questions';
