/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyQuizQuestionResponse } from '../../models/daily-quiz-question-response';
import { UpdateDailyQuizQuestionRequest } from '../../models/update-daily-quiz-question-request';

export interface UpdateAssignment2$Params {
  id: number;
      body: UpdateDailyQuizQuestionRequest
}

export function updateAssignment2(http: HttpClient, rootUrl: string, params: UpdateAssignment2$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyQuizQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAssignment2.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyQuizQuestionResponse>;
    })
  );
}

updateAssignment2.PATH = '/daily-quiz-questions/{id}';
