/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageLanguageResponse } from '../../models/page-language-response';

export interface GetLanguages$Params {
  name?: string;
  code?: string;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getLanguages(http: HttpClient, rootUrl: string, params?: GetLanguages$Params, context?: HttpContext): Observable<StrictHttpResponse<PageLanguageResponse>> {
  const rb = new RequestBuilder(rootUrl, getLanguages.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('code', params.code, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageLanguageResponse>;
    })
  );
}

getLanguages.PATH = '/languages';
