/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LanguageResponse } from '../../models/language-response';
import { UpdateLanguageRequest } from '../../models/update-language-request';

export interface UpdateLanguage$Params {
  uuid: string;
      body: UpdateLanguageRequest
}

export function updateLanguage(http: HttpClient, rootUrl: string, params: UpdateLanguage$Params, context?: HttpContext): Observable<StrictHttpResponse<LanguageResponse>> {
  const rb = new RequestBuilder(rootUrl, updateLanguage.PATH, 'patch');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LanguageResponse>;
    })
  );
}

updateLanguage.PATH = '/languages/{uuid}';
