/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindRolesQuery } from '../../models/find-roles-query';
import { PageRoleResponse } from '../../models/page-role-response';

export interface GetRoles$Params {
  query: FindRolesQuery;
}

export function getRoles(http: HttpClient, rootUrl: string, params: GetRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<PageRoleResponse>> {
  const rb = new RequestBuilder(rootUrl, getRoles.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageRoleResponse>;
    })
  );
}

getRoles.PATH = '/roles';
