/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantResponse } from '../../models/tenant-response';
import { UpdateTenantRequest } from '../../models/update-tenant-request';

export interface UpdateOwnTenant$Params {
      body?: UpdateTenantRequest
}

export function updateOwnTenant(http: HttpClient, rootUrl: string, params?: UpdateOwnTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantResponse>> {
  const rb = new RequestBuilder(rootUrl, updateOwnTenant.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantResponse>;
    })
  );
}

updateOwnTenant.PATH = '/admin/tenant';
