/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTenantStaffRequest } from '../../models/create-tenant-staff-request';
import { StaffResponse } from '../../models/staff-response';

export interface CreateTenantAdmin$Params {
      body: CreateTenantStaffRequest
}

export function createTenantAdmin(http: HttpClient, rootUrl: string, params: CreateTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<StaffResponse>> {
  const rb = new RequestBuilder(rootUrl, createTenantAdmin.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffResponse>;
    })
  );
}

createTenantAdmin.PATH = '/platform/staff/tenant-admin';
