/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlatformStaffDetailsResponse } from '../../models/platform-staff-details-response';

export interface GetPlatformStaffDetails$Params {
  uuid: string;
}

export function getPlatformStaffDetails(http: HttpClient, rootUrl: string, params: GetPlatformStaffDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformStaffDetailsResponse>> {
  const rb = new RequestBuilder(rootUrl, getPlatformStaffDetails.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlatformStaffDetailsResponse>;
    })
  );
}

getPlatformStaffDetails.PATH = '/platform/staff/{uuid}';
