/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindStaffQuery } from '../../models/find-staff-query';
import { PageStaffResponse } from '../../models/page-staff-response';

export interface ListPlatformStaff$Params {
  query: FindStaffQuery;
}

export function listPlatformStaff(http: HttpClient, rootUrl: string, params: ListPlatformStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStaffResponse>> {
  const rb = new RequestBuilder(rootUrl, listPlatformStaff.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageStaffResponse>;
    })
  );
}

listPlatformStaff.PATH = '/platform/staff';
