/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StaffResponse } from '../../models/staff-response';
import { UpdatePlatformStaffRequest } from '../../models/update-platform-staff-request';

export interface UpdatePlatformStaff$Params {
  uuid: string;
      body: UpdatePlatformStaffRequest
}

export function updatePlatformStaff(http: HttpClient, rootUrl: string, params: UpdatePlatformStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<StaffResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePlatformStaff.PATH, 'patch');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffResponse>;
    })
  );
}

updatePlatformStaff.PATH = '/platform/staff/{uuid}';
