/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignWeeklyQuizQuestionRequest } from '../../models/assign-weekly-quiz-question-request';
import { WeeklyQuizQuestionResponse } from '../../models/weekly-quiz-question-response';

export interface AssignQuestion$Params {
      body: AssignWeeklyQuizQuestionRequest
}

export function assignQuestion(http: HttpClient, rootUrl: string, params: AssignQuestion$Params, context?: HttpContext): Observable<StrictHttpResponse<WeeklyQuizQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, assignQuestion.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeeklyQuizQuestionResponse>;
    })
  );
}

assignQuestion.PATH = '/weekly-quiz-questions';
