/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageWeeklyQuizQuestionResponse } from '../../models/page-weekly-quiz-question-response';

export interface GetWeeklyQuizQuestions$Params {
  weeklyQuizUuid?: string;
  questionUuid?: string;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getWeeklyQuizQuestions(http: HttpClient, rootUrl: string, params?: GetWeeklyQuizQuestions$Params, context?: HttpContext): Observable<StrictHttpResponse<PageWeeklyQuizQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, getWeeklyQuizQuestions.PATH, 'get');
  if (params) {
    rb.query('weeklyQuizUuid', params.weeklyQuizUuid, {});
    rb.query('questionUuid', params.questionUuid, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageWeeklyQuizQuestionResponse>;
    })
  );
}

getWeeklyQuizQuestions.PATH = '/weekly-quiz-questions';
