/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateWeeklyQuizQuestionRequest } from '../../models/update-weekly-quiz-question-request';
import { WeeklyQuizQuestionResponse } from '../../models/weekly-quiz-question-response';

export interface UpdateAssignment$Params {
  id: number;
      body: UpdateWeeklyQuizQuestionRequest
}

export function updateAssignment(http: HttpClient, rootUrl: string, params: UpdateAssignment$Params, context?: HttpContext): Observable<StrictHttpResponse<WeeklyQuizQuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAssignment.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeeklyQuizQuestionResponse>;
    })
  );
}

updateAssignment.PATH = '/weekly-quiz-questions/{id}';
