/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantStaffDetailsResponse } from '../../models/tenant-staff-details-response';

export interface GetTenantStaffDetails$Params {
  uuid: string;
}

export function getTenantStaffDetails(http: HttpClient, rootUrl: string, params: GetTenantStaffDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantStaffDetailsResponse>> {
  const rb = new RequestBuilder(rootUrl, getTenantStaffDetails.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantStaffDetailsResponse>;
    })
  );
}

getTenantStaffDetails.PATH = '/admin/staff/{uuid}';
