/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StaffResponse } from '../../models/staff-response';

export interface ListTenantStaff$Params {
  tenantUuid?: string;
}

export function listTenantStaff(http: HttpClient, rootUrl: string, params?: ListTenantStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StaffResponse>>> {
  const rb = new RequestBuilder(rootUrl, listTenantStaff.PATH, 'get');
  if (params) {
    rb.query('tenantUuid', params.tenantUuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StaffResponse>>;
    })
  );
}

listTenantStaff.PATH = '/admin/staff';
