/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageStaffResponse } from '../../models/page-staff-response';

export interface ListTenantStaff$Params {
  tenantUuid?: string;
  firstname?: string;
  email?: string;
  lastname?: string;
  positionName?: string;
  page?: number;
  size?: number;
  sortBy?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function listTenantStaff(http: HttpClient, rootUrl: string, params?: ListTenantStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStaffResponse>> {
  const rb = new RequestBuilder(rootUrl, listTenantStaff.PATH, 'get');
  if (params) {
    rb.query('tenantUuid', params.tenantUuid, {});
    rb.query('firstname', params.firstname, {});
    rb.query('email', params.email, {});
    rb.query('lastname', params.lastname, {});
    rb.query('positionName', params.positionName, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageStaffResponse>;
    })
  );
}

listTenantStaff.PATH = '/admin/staff';
