/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuizSessionResponse } from '../../models/quiz-session-response';
import { StartQuizSessionRequest } from '../../models/start-quiz-session-request';

export interface StartSession$Params {
      body: StartQuizSessionRequest
}

export function startSession(http: HttpClient, rootUrl: string, params: StartSession$Params, context?: HttpContext): Observable<StrictHttpResponse<QuizSessionResponse>> {
  const rb = new RequestBuilder(rootUrl, startSession.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuizSessionResponse>;
    })
  );
}

startSession.PATH = '/quiz-sessions';
