/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateQuestionOptionForm } from '../../models/create-question-option-form';
import { QuestionOptionResponseDto } from '../../models/question-option-response-dto';

export interface CreateQuestionOption$Params {
      body?: CreateQuestionOptionForm
}

export function createQuestionOption(http: HttpClient, rootUrl: string, params?: CreateQuestionOption$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionOptionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createQuestionOption.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuestionOptionResponseDto>;
    })
  );
}

createQuestionOption.PATH = '/question-options';
