/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuestionOptionResponseDto } from '../../models/question-option-response-dto';
import { UpdateQuestionOptionForm } from '../../models/update-question-option-form';

export interface UpdateQuestionOption$Params {
  uuid: string;
      body?: UpdateQuestionOptionForm
}

export function updateQuestionOption(http: HttpClient, rootUrl: string, params: UpdateQuestionOption$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionOptionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateQuestionOption.PATH, 'patch');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuestionOptionResponseDto>;
    })
  );
}

updateQuestionOption.PATH = '/question-options/{uuid}';
